name: Storybook development

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2

      - name: Build storybook
        run: |
          yarn install
          yarn build-storybook
        env:
          CI: true

      - name: Deploy storybook
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: storybook
          publish_dir: ./storybook-static
